### ISSUE TITLE
Missing etcd versions (older versions, including v2.x)

### ISSUE THREAD

**Issue by MPV** [particledecay/asdf-etcd#1]
I've tried looking through the code but I haven't yet found why it only returns a few versions, and in particular is missing `v2.x` versions that I'd like to install, for example: https://github.com/etcd-io/etcd/releases/tag/v2.3.8

Any ideas?

These are all versions I get with this plugin:

```bash
$ asdf list all etcd
v3.4.13
v3.4.12
v3.4.11
v3.4.10
v3.4.9
v3.4.8
v3.4.7
v3.4.6
v3.4.5
v3.4.4
v3.4.3
v3.4.2
v3.4.1
v3.4.0-rc.4
v3.4.0-rc.3
v3.4.0
v3.3.25
v3.3.24
v3.3.23
v3.3.22
v3.3.21
v3.3.20
v3.3.19
v3.3.18
v3.3.17
v3.2.31
v3.2.30
v3.2.29
v3.2.28
v3.2.27
``` 

Older versions aren't included either, for example 3.2.26:
https://github.com/etcd-io/etcd/releases/tag/v3.2.26

The above maybe can be solved with pagination or similar, but I also noticed that I'm not able to install older (but existing) versions either:

```bash
$ asdf install etcd v2.3.8
Downloading etcdctl version v2.3.8 from
Error: etcdctl version v2.3.8 not found
```

**Comment by particledecay** [comment]
@MPV it looks like the reasoning for this is that GitHub API v3 returns a maximum of 30 results by default. I'd have to implement pagination handling in order to make this work, and at first glance it doesn't look like GitHub's response provides an easy way to view total result size.
